package com.syy.moduledbbase.db.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.syy.moduledbbase.db.entity.modulecommon.FlyRecord;
import com.syy.moduledbbase.db.entity.modulecommon.FlyRecordDetail;
import com.syy.moduledbbase.db.entity.modulecommon.PatrolTask;
import com.syy.moduledbbase.db.entity.modulecommon.TaskData;
import com.syy.moduledbbase.db.entity.modulecommon.TaskMarker;
import com.syy.moduledbbase.db.entity.modulecommon.TaskParams;
import com.syy.moduledbbase.db.entity.moduleuav.FineStep;
import com.syy.moduledbbase.db.entity.moduleuav.ImageInfo;
import com.syy.moduledbbase.db.entity.moduleuav.channel.ChannelAirTaskBean;
import com.syy.moduledbbase.db.entity.moduleuav.fine.FineAirTaskBean;
import com.syy.moduledbbase.db.entity.moduleuav.panorama.PanoramaAirTaskBean;
import com.syy.moduledbbase.db.entity.moduleuav.plantask.PlanTask;
import com.syy.moduledbbase.db.entity.moduleuav.plantask.channel.PlanChannelAirTask;
import com.syy.moduledbbase.db.entity.moduleuav.plantask.fine.PlanFineAirTask;
import com.syy.moduledbbase.db.entity.moduleuav.plantask.line.ChildRoutes;
import com.syy.moduledbbase.db.entity.moduleuav.pointcloud.PointCloudAirTaskBean;

import com.syy.moduledbbase.db.greedao.FlyRecordDao;
import com.syy.moduledbbase.db.greedao.FlyRecordDetailDao;
import com.syy.moduledbbase.db.greedao.PatrolTaskDao;
import com.syy.moduledbbase.db.greedao.TaskDataDao;
import com.syy.moduledbbase.db.greedao.TaskMarkerDao;
import com.syy.moduledbbase.db.greedao.TaskParamsDao;
import com.syy.moduledbbase.db.greedao.FineStepDao;
import com.syy.moduledbbase.db.greedao.ImageInfoDao;
import com.syy.moduledbbase.db.greedao.ChannelAirTaskBeanDao;
import com.syy.moduledbbase.db.greedao.FineAirTaskBeanDao;
import com.syy.moduledbbase.db.greedao.PanoramaAirTaskBeanDao;
import com.syy.moduledbbase.db.greedao.PlanTaskDao;
import com.syy.moduledbbase.db.greedao.PlanChannelAirTaskDao;
import com.syy.moduledbbase.db.greedao.PlanFineAirTaskDao;
import com.syy.moduledbbase.db.greedao.ChildRoutesDao;
import com.syy.moduledbbase.db.greedao.PointCloudAirTaskBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig flyRecordDaoConfig;
    private final DaoConfig flyRecordDetailDaoConfig;
    private final DaoConfig patrolTaskDaoConfig;
    private final DaoConfig taskDataDaoConfig;
    private final DaoConfig taskMarkerDaoConfig;
    private final DaoConfig taskParamsDaoConfig;
    private final DaoConfig fineStepDaoConfig;
    private final DaoConfig imageInfoDaoConfig;
    private final DaoConfig channelAirTaskBeanDaoConfig;
    private final DaoConfig fineAirTaskBeanDaoConfig;
    private final DaoConfig panoramaAirTaskBeanDaoConfig;
    private final DaoConfig planTaskDaoConfig;
    private final DaoConfig planChannelAirTaskDaoConfig;
    private final DaoConfig planFineAirTaskDaoConfig;
    private final DaoConfig childRoutesDaoConfig;
    private final DaoConfig pointCloudAirTaskBeanDaoConfig;

    private final FlyRecordDao flyRecordDao;
    private final FlyRecordDetailDao flyRecordDetailDao;
    private final PatrolTaskDao patrolTaskDao;
    private final TaskDataDao taskDataDao;
    private final TaskMarkerDao taskMarkerDao;
    private final TaskParamsDao taskParamsDao;
    private final FineStepDao fineStepDao;
    private final ImageInfoDao imageInfoDao;
    private final ChannelAirTaskBeanDao channelAirTaskBeanDao;
    private final FineAirTaskBeanDao fineAirTaskBeanDao;
    private final PanoramaAirTaskBeanDao panoramaAirTaskBeanDao;
    private final PlanTaskDao planTaskDao;
    private final PlanChannelAirTaskDao planChannelAirTaskDao;
    private final PlanFineAirTaskDao planFineAirTaskDao;
    private final ChildRoutesDao childRoutesDao;
    private final PointCloudAirTaskBeanDao pointCloudAirTaskBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        flyRecordDaoConfig = daoConfigMap.get(FlyRecordDao.class).clone();
        flyRecordDaoConfig.initIdentityScope(type);

        flyRecordDetailDaoConfig = daoConfigMap.get(FlyRecordDetailDao.class).clone();
        flyRecordDetailDaoConfig.initIdentityScope(type);

        patrolTaskDaoConfig = daoConfigMap.get(PatrolTaskDao.class).clone();
        patrolTaskDaoConfig.initIdentityScope(type);

        taskDataDaoConfig = daoConfigMap.get(TaskDataDao.class).clone();
        taskDataDaoConfig.initIdentityScope(type);

        taskMarkerDaoConfig = daoConfigMap.get(TaskMarkerDao.class).clone();
        taskMarkerDaoConfig.initIdentityScope(type);

        taskParamsDaoConfig = daoConfigMap.get(TaskParamsDao.class).clone();
        taskParamsDaoConfig.initIdentityScope(type);

        fineStepDaoConfig = daoConfigMap.get(FineStepDao.class).clone();
        fineStepDaoConfig.initIdentityScope(type);

        imageInfoDaoConfig = daoConfigMap.get(ImageInfoDao.class).clone();
        imageInfoDaoConfig.initIdentityScope(type);

        channelAirTaskBeanDaoConfig = daoConfigMap.get(ChannelAirTaskBeanDao.class).clone();
        channelAirTaskBeanDaoConfig.initIdentityScope(type);

        fineAirTaskBeanDaoConfig = daoConfigMap.get(FineAirTaskBeanDao.class).clone();
        fineAirTaskBeanDaoConfig.initIdentityScope(type);

        panoramaAirTaskBeanDaoConfig = daoConfigMap.get(PanoramaAirTaskBeanDao.class).clone();
        panoramaAirTaskBeanDaoConfig.initIdentityScope(type);

        planTaskDaoConfig = daoConfigMap.get(PlanTaskDao.class).clone();
        planTaskDaoConfig.initIdentityScope(type);

        planChannelAirTaskDaoConfig = daoConfigMap.get(PlanChannelAirTaskDao.class).clone();
        planChannelAirTaskDaoConfig.initIdentityScope(type);

        planFineAirTaskDaoConfig = daoConfigMap.get(PlanFineAirTaskDao.class).clone();
        planFineAirTaskDaoConfig.initIdentityScope(type);

        childRoutesDaoConfig = daoConfigMap.get(ChildRoutesDao.class).clone();
        childRoutesDaoConfig.initIdentityScope(type);

        pointCloudAirTaskBeanDaoConfig = daoConfigMap.get(PointCloudAirTaskBeanDao.class).clone();
        pointCloudAirTaskBeanDaoConfig.initIdentityScope(type);

        flyRecordDao = new FlyRecordDao(flyRecordDaoConfig, this);
        flyRecordDetailDao = new FlyRecordDetailDao(flyRecordDetailDaoConfig, this);
        patrolTaskDao = new PatrolTaskDao(patrolTaskDaoConfig, this);
        taskDataDao = new TaskDataDao(taskDataDaoConfig, this);
        taskMarkerDao = new TaskMarkerDao(taskMarkerDaoConfig, this);
        taskParamsDao = new TaskParamsDao(taskParamsDaoConfig, this);
        fineStepDao = new FineStepDao(fineStepDaoConfig, this);
        imageInfoDao = new ImageInfoDao(imageInfoDaoConfig, this);
        channelAirTaskBeanDao = new ChannelAirTaskBeanDao(channelAirTaskBeanDaoConfig, this);
        fineAirTaskBeanDao = new FineAirTaskBeanDao(fineAirTaskBeanDaoConfig, this);
        panoramaAirTaskBeanDao = new PanoramaAirTaskBeanDao(panoramaAirTaskBeanDaoConfig, this);
        planTaskDao = new PlanTaskDao(planTaskDaoConfig, this);
        planChannelAirTaskDao = new PlanChannelAirTaskDao(planChannelAirTaskDaoConfig, this);
        planFineAirTaskDao = new PlanFineAirTaskDao(planFineAirTaskDaoConfig, this);
        childRoutesDao = new ChildRoutesDao(childRoutesDaoConfig, this);
        pointCloudAirTaskBeanDao = new PointCloudAirTaskBeanDao(pointCloudAirTaskBeanDaoConfig, this);

        registerDao(FlyRecord.class, flyRecordDao);
        registerDao(FlyRecordDetail.class, flyRecordDetailDao);
        registerDao(PatrolTask.class, patrolTaskDao);
        registerDao(TaskData.class, taskDataDao);
        registerDao(TaskMarker.class, taskMarkerDao);
        registerDao(TaskParams.class, taskParamsDao);
        registerDao(FineStep.class, fineStepDao);
        registerDao(ImageInfo.class, imageInfoDao);
        registerDao(ChannelAirTaskBean.class, channelAirTaskBeanDao);
        registerDao(FineAirTaskBean.class, fineAirTaskBeanDao);
        registerDao(PanoramaAirTaskBean.class, panoramaAirTaskBeanDao);
        registerDao(PlanTask.class, planTaskDao);
        registerDao(PlanChannelAirTask.class, planChannelAirTaskDao);
        registerDao(PlanFineAirTask.class, planFineAirTaskDao);
        registerDao(ChildRoutes.class, childRoutesDao);
        registerDao(PointCloudAirTaskBean.class, pointCloudAirTaskBeanDao);
    }
    
    public void clear() {
        flyRecordDaoConfig.clearIdentityScope();
        flyRecordDetailDaoConfig.clearIdentityScope();
        patrolTaskDaoConfig.clearIdentityScope();
        taskDataDaoConfig.clearIdentityScope();
        taskMarkerDaoConfig.clearIdentityScope();
        taskParamsDaoConfig.clearIdentityScope();
        fineStepDaoConfig.clearIdentityScope();
        imageInfoDaoConfig.clearIdentityScope();
        channelAirTaskBeanDaoConfig.clearIdentityScope();
        fineAirTaskBeanDaoConfig.clearIdentityScope();
        panoramaAirTaskBeanDaoConfig.clearIdentityScope();
        planTaskDaoConfig.clearIdentityScope();
        planChannelAirTaskDaoConfig.clearIdentityScope();
        planFineAirTaskDaoConfig.clearIdentityScope();
        childRoutesDaoConfig.clearIdentityScope();
        pointCloudAirTaskBeanDaoConfig.clearIdentityScope();
    }

    public FlyRecordDao getFlyRecordDao() {
        return flyRecordDao;
    }

    public FlyRecordDetailDao getFlyRecordDetailDao() {
        return flyRecordDetailDao;
    }

    public PatrolTaskDao getPatrolTaskDao() {
        return patrolTaskDao;
    }

    public TaskDataDao getTaskDataDao() {
        return taskDataDao;
    }

    public TaskMarkerDao getTaskMarkerDao() {
        return taskMarkerDao;
    }

    public TaskParamsDao getTaskParamsDao() {
        return taskParamsDao;
    }

    public FineStepDao getFineStepDao() {
        return fineStepDao;
    }

    public ImageInfoDao getImageInfoDao() {
        return imageInfoDao;
    }

    public ChannelAirTaskBeanDao getChannelAirTaskBeanDao() {
        return channelAirTaskBeanDao;
    }

    public FineAirTaskBeanDao getFineAirTaskBeanDao() {
        return fineAirTaskBeanDao;
    }

    public PanoramaAirTaskBeanDao getPanoramaAirTaskBeanDao() {
        return panoramaAirTaskBeanDao;
    }

    public PlanTaskDao getPlanTaskDao() {
        return planTaskDao;
    }

    public PlanChannelAirTaskDao getPlanChannelAirTaskDao() {
        return planChannelAirTaskDao;
    }

    public PlanFineAirTaskDao getPlanFineAirTaskDao() {
        return planFineAirTaskDao;
    }

    public ChildRoutesDao getChildRoutesDao() {
        return childRoutesDao;
    }

    public PointCloudAirTaskBeanDao getPointCloudAirTaskBeanDao() {
        return pointCloudAirTaskBeanDao;
    }

}
